### ISSUE TITLE
All default meshes included should be 3D printable

### ISSUE THREAD

**Issue by romainbou** [MyMiniFactory/CharacterCreator#1]
For the generated Character to be 3D printable, all parts should also pass the printability tests.

For instance this mesh isn't watertight:
CharacterCreator/public/models/hand/robot_hand_L.glb

Converted to STL doesn't pass the check here:
https://myminifactory.github.io/3DPrintingMeshRepair

**Comment by adrian-delgado** [comment]
No longer relevant as each customizer owner will have the responsibility to ensure their parts are 3D-printable.
